// <auto-generated />
namespace CalLicenseDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LicenseModelCHanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LicenseModelCHanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201702051704590_LicenseModelCHanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
